### ISSUE TITLE
求助作者关于项目启动的问题

### ISSUE THREAD

**Issue by wangwenyu0805** [congjinruo/JulyNovel-React#3]
项目前端运行启动之后，会有这个报错：
Uncaught Error: Cannot find module './__ generated __/HomeQuery.graphql'
，求作者大神告知如何解决，谢谢了

**Comment by congjinruo** [comment]
这个要先`yarn run relay`的，然后再`yarn start`

**Comment by congjinruo** [comment]
> 
> 
> 项目前端运行启动之后，会有这个报错：
> Uncaught Error: Cannot find module './__ generated __/HomeQuery.graphql'
> ，求作者大神告知如何解决，谢谢了

我更新了项目说明文件，你可以自己去看下

**Comment by wangwenyu0805** [comment]
> > 项目前端运行启动之后，会有这个报错：
> > Uncaught Error: Cannot find module './__ generated __/HomeQuery.graphql'
> > ，求作者大神告知如何解决，谢谢了
> 
> 我更新了项目说明文件，你可以自己去看下

已经启动成功了，谢谢，3Q
